version: '3.8'

services:
  search_engine:
    build:
      context: .
      dockerfile: search_engine/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./search_engine:/app/search_engine
    environment:
      - PYTHONUNBUFFERED=1
